## ---(Wed Jul 14 09:24:20 2021)---
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runcell(0, 'C:/Users/LIONS/.spyder-py3/untitled0.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/untitled0.py')
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/untitled1.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스프레이차트_kyj.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스프레이차트_kyj.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/높은 구속 헛스윙률.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스프레이차트_kyj.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스프레이차트_kyj.py', wdir='C:/Users/LIONS/Desktop/고교야구')

## ---(Wed Jul 14 15:03:03 2021)---
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스프레이차트_kyj.py', wdir='C:/Users/LIONS/Desktop/고교야구')

## ---(Wed Jul 14 16:05:00 2021)---
runfile('C:/Users/LIONS/Desktop/고교야구/스프레이차트_kyj.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')

## ---(Wed Jul 14 17:25:15 2021)---
runfile('C:/Users/LIONS/Desktop/고교야구/파일 병합.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스프레이차트_kyj.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/높은 구속 헛스윙률.py', wdir='C:/Users/LIONS/Desktop/고교야구')

## ---(Thu Jul 15 09:10:31 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 3주/최고타구속도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 3주')
runfile('C:/Users/LIONS/.spyder-py3/7월 3주/Zswing-Oswing.py', wdir='C:/Users/LIONS/.spyder-py3/7월 3주')
runfile('C:/Users/LIONS/Desktop/고교야구/스프레이차트_kyj.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스프레이차트_kyj.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')

## ---(Thu Jul 15 15:02:36 2021)---
runfile('C:/Users/LIONS/Desktop/고교야구/untitled0.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/.spyder-py3/7월 3주/외인 투수 후보 구종별 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/7월 3주')
runfile('C:/Users/LIONS/.spyder-py3/7월 3주/외인 투수 후보 무브먼트.py', wdir='C:/Users/LIONS/.spyder-py3/7월 3주')

## ---(Fri Jul 16 09:26:30 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 3주')
runfile('C:/Users/LIONS/.spyder-py3/7월 3주/외인 투수 후보 구종별 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/7월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/7월 1주/2아웃 상황 투구 비교.py')
runcell('전체/2아웃 로케이션 비교', 'C:/Users/LIONS/.spyder-py3/7월 1주/2아웃 상황 투구 비교.py')
runcell(3, 'C:/Users/LIONS/.spyder-py3/7월 1주/2아웃 상황 투구 비교.py')
runcell('전체/2아웃 zone percentage', 'C:/Users/LIONS/.spyder-py3/7월 1주/2아웃 상황 투구 비교.py')
runfile('C:/Users/LIONS/.spyder-py3/7월 3주/외인 투수 후보 무브먼트.py', wdir='C:/Users/LIONS/.spyder-py3/7월 3주')

## ---(Mon Jul 19 13:57:57 2021)---
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/김상수 바빕.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')

## ---(Tue Jul 20 10:31:23 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/김상수 바빕.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/7월 4주/김상수 바빕.py')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/김상수 바빕.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/바빕 변화 추이.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/바빕 변화 추이.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/스윗스팟 및 강한타구비율 전년도 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')

## ---(Tue Jul 20 15:29:28 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/스윗스팟 및 강한타구비율 전년도 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/바빕 변화 추이.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')

## ---(Thu Jul 22 17:32:46 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')

## ---(Fri Jul 23 10:02:00 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/pitch_type_classification_2D.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/pitch_type_classification_2D.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/pitch_type_classification_2D.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/2군 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/7월 1주/2아웃 상황 투구 비교.py')
runcell('전체/2아웃 구속 분포 비교', 'C:/Users/LIONS/.spyder-py3/7월 1주/2아웃 상황 투구 비교.py')
runcell('전체/2아웃 로케이션 비교', 'C:/Users/LIONS/.spyder-py3/7월 1주/2아웃 상황 투구 비교.py')
runcell(3, 'C:/Users/LIONS/.spyder-py3/7월 1주/2아웃 상황 투구 비교.py')
runfile('C:/Users/LIONS/.spyder-py3/7월 2주/배럴.py', wdir='C:/Users/LIONS/.spyder-py3/7월 2주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/2군 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/전체 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/7월 4주/전체 구종분류.py')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/전체 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')

## ---(Mon Jul 26 10:34:56 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/전체 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')

## ---(Mon Jul 26 11:32:59 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/전체 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/2군 투수 분포.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/투수 유사도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/7월 4주/투수 유사도.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/7월 4주/투수 유사도.py')

## ---(Tue Jul 27 10:43:12 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/전체 투수 분포.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/투수 유사도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 유사도(구속 배제).py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/2군 존투구율 및 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/7월 5주/2군 존투구율 및 헛스윙률.py')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/리그 로케이션 피장타율.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/리그 로케이션 피장타율.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/리그 로케이션 바빕.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/리그 로케이션 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/2군 존투구율 및 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/7월 5주/untitled3.py')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/7월 5주/untitled3.py')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')

## ---(Fri Jul 30 09:22:31 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/리그 로케이션 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/리그 로케이션 피장타율.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/리그 로케이션 바빕.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/리그 로케이션 피장타율.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/6월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/6월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/내야 그림 그리기.py')
runfile('C:/Users/LIONS/.spyder-py3/내야 그림 그리기.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/6월 4주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/6월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/6월 4주/untitled2.py')
runfile('C:/Users/LIONS/.spyder-py3/6월 4주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/6월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/6월 4주/untitled2.py')
runfile('C:/Users/LIONS/.spyder-py3/6월 4주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/6월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/스윗스팟 일러.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 2주/구장 그리기.py', wdir='C:/Users/LIONS/.spyder-py3/7월 2주')
runfile('C:/Users/LIONS/.spyder-py3/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/라팍 그리기(정면).py', wdir='C:/Users/LIONS/.spyder-py3')

## ---(Mon Aug  2 09:41:50 2021)---
runfile('C:/Users/LIONS/.spyder-py3/라팍 그리기(정면).py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/스윗스팟 일러.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/리그 로케이션 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')

## ---(Tue Aug  3 13:40:01 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/릴리즈 포인트 비교.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')

## ---(Wed Aug  4 13:01:00 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/릴리즈 포인트 비교.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/릴리즈 포인트 비교.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/2군 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/릴리즈 포인트 비교.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/릴리즈 포인트 비교.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/릴리즈 포인트 비교.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/릴리즈 포인트 비교.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')

## ---(Tue Aug 10 13:47:16 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')

## ---(Tue Aug 10 15:42:48 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/구속 삼진률 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/구속 삼진률 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 2주/구속 삼진률 상관관계.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/구속 삼진률 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/구속 삼진률 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/직구구속 K9 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/개인 로케이션 분포도 2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')

## ---(Wed Aug 11 13:26:13 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/구속에 대한 도달거리 차이.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')

## ---(Thu Aug 12 13:11:37 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 타격성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/구속에 따른 도달거리 차이.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 타격성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Fri Aug 13 10:58:28 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 타격성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Fri Aug 13 13:54:23 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 타격성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 투구성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Tue Aug 17 09:46:23 2021)---
runfile('C:/Users/LIONS/Desktop/고교야구/파일 병합.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runcell(0, 'C:/Users/LIONS/Desktop/고교야구/파일 병합.py')
runcell(1, 'C:/Users/LIONS/Desktop/고교야구/파일 병합.py')
runfile('C:/Users/LIONS/Desktop/고교야구/untitled0.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/untitled1.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/Desktop/고교야구/untitled0.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스프레이차트 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/Desktop/고교야구/스트라이크존.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/황사기 청룡기 합본 타격스탯.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스프레이차트 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스트라이크존 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스프레이차트 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스프레이차트 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')

## ---(Tue Aug 17 15:25:10 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스프레이차트 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스트라이크존 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')

## ---(Tue Aug 17 15:37:27 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스트라이크존 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스프레이차트 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')

## ---(Tue Aug 17 15:41:48 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스프레이차트 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/스트라이크존 합본.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')

## ---(Wed Aug 18 13:57:28 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')

## ---(Thu Aug 19 09:12:00 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/존 분할 그림.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')

## ---(Fri Aug 20 12:15:04 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/개인 로케이션 분포도 3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/Desktop/고교야구/untitled0.py', wdir='C:/Users/LIONS/Desktop/고교야구')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/구종 속성 평균.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류2.py')

## ---(Sat Aug 21 10:40:36 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/7월 4주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/7월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 타격성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled5.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 타격성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled5.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Sun Aug 22 12:26:32 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 타격성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/6월 4주/팀별 내야 땅볼 처리율.py')
runfile('C:/Users/LIONS/.spyder-py3/6월 4주/팀별 내야 땅볼 처리율.py', wdir='C:/Users/LIONS/.spyder-py3/6월 4주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/6월 4주/팀별 내야 땅볼 처리율.py')
runfile('C:/Users/LIONS/.spyder-py3/6월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/6월 4주')

## ---(Mon Aug 23 14:05:41 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 타격성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Tue Aug 24 16:15:09 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/개인 로케이션 분포도 3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')

## ---(Tue Aug 24 18:29:08 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/개인 로케이션 분포도 3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')

## ---(Wed Aug 25 10:19:19 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/AAA 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runcell(1, 'C:/Users/LIONS/.spyder-py3/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2(교차).py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Thu Aug 26 10:48:21 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/타자 리더보드.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/파일 병합.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/xwOBA.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')

## ---(Thu Aug 26 16:40:06 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/xwOBA.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/xwOBA.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/xwOBA.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/xwOBA 2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Thu Aug 26 18:01:17 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Fri Aug 27 10:31:38 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/존 분할 그림.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')

## ---(Tue Aug 31 13:20:01 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/시프트 자료.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 구종별 스윙 및 헛스윙.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 구종별 스윙 및 헛스윙.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 구종별 스윙 및 헛스윙.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')

## ---(Wed Sep  1 11:16:29 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 구종별 스윙 및 헛스윙.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/로케이션 별 헛스윙 비교.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 로케이션 별 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 로케이션 별 장타율.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 로케이션 별 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/리그 로케이션 별 장타율.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 로케이션 별 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 4주/타자 구종별 장타율.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 구종별 장타율.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 로케이션 별 헛스윙률.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타자 구종별 스윙 및 헛스윙.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/리그 전체 구종분류.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')

## ---(Thu Sep  2 09:32:22 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/K9 스윙률 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/구종 속성.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/x스탯.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/배럴타구 타율 및 장타율.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 4주/배럴타구 타율 및 장타율.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/배럴타구 타율 및 장타율.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/K-BB-plate_discipline 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/HR9-기타스탯 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/K-BB-plate_discipline 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/HR9-기타스탯 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/K-BB-plate_discipline 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')

## ---(Fri Sep  3 10:00:58 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/YBY HR9 (팀 정보 추가).py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 4주/YBY HR9 (팀 정보 추가).py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 4주/YBY HR9 (팀 정보 추가).py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/8월 4주/YBY HR9 (팀 정보 추가).py')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/YBY HR9 (팀 정보 추가).py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 4주/YBY HR9 (팀 정보 추가).py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 4주/YBY HR9 (팀 정보 추가).py')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/타구 유형별 타율 장타율.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/YBY HR9 (팀 정보 추가).py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')

## ---(Sat Sep  4 12:01:28 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/존 별 swing 및 take 시각화.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/15경기 스윙률.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/존 별 swing 및 take 시각화.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 4주/존 별 swing 및 take 시각화.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/존 별 swing 및 take 시각화.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/개인 로케이션 분포도 3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/존 별 swing 및 take 시각화.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/개인 로케이션 분포도 3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/존 별 swing 및 take 시각화.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/개인 로케이션 분포도 3.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 4주/존 별 swing 및 take 시각화.py', wdir='C:/Users/LIONS/.spyder-py3/8월 4주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')

## ---(Sun Sep  5 10:44:10 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/직구구속 BB9 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/직구구속 K9 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/직구구속 BB9 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/직구구속 K9 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/7월 5주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/릴리즈 포인트 비교.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/직구구속 K9 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/직구구속 K9 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/직구구속 K9 상관관계.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/릴리즈 포인트 비교.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 1주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 1주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Tue Sep  7 13:04:51 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/삼성 불펜투수 첫타자 사사구 비율.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/팀별 불펜투수 첫타자 사사구 비율.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/삼성 불펜투수 첫타자 사사구 비율.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Wed Sep  8 12:14:28 2021)---
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/팀별 불펜투수 첫타자 사사구 비율2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/투수 스탯 - HR9 관계.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/투수 스탯 - HR9 관계.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')

## ---(Thu Sep  9 16:21:35 2021)---
runfile('C:/Users/LIONS/.spyder-py3/7월 5주/투수 구종 별 속성 비교.py', wdir='C:/Users/LIONS/.spyder-py3/7월 5주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Fri Sep 10 13:02:21 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Tue Sep 14 12:34:04 2021)---
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/9월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/9월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종 무브먼트 comparison 2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 3주/타자 리더보드.py', wdir='C:/Users/LIONS/.spyder-py3/8월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종 무브먼트 comparison 2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Wed Sep 15 13:41:33 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/R2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종 무브먼트 comparison 2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Wed Sep 15 18:07:34 2021)---
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/파일 병합.py', wdir='C:/Users/LIONS/.spyder-py3')
runcell(0, 'C:/Users/LIONS/.spyder-py3/파일 병합.py')
runfile('C:/Users/LIONS/.spyder-py3/파일 병합.py', wdir='C:/Users/LIONS/.spyder-py3')
runcell(1, 'C:/Users/LIONS/.spyder-py3/파일 병합.py')
runfile('C:/Users/LIONS/.spyder-py3/파일 병합.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')

## ---(Thu Sep 16 22:03:13 2021)---
runfile('C:/Users/LIONS/.spyder-py3/파일 병합2.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')

## ---(Fri Sep 17 13:12:23 2021)---
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/파일 병합.py', wdir='C:/Users/LIONS/.spyder-py3')
runcell(0, 'C:/Users/LIONS/.spyder-py3/파일 병합2.py')
runfile('C:/Users/LIONS/.spyder-py3/파일 병합2.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/파일 병합.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/R2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runcell(1, 'C:/Users/LIONS/.spyder-py3/untitled1.py')

## ---(Thu Sep 23 10:38:56 2021)---
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/팀별 불펜투수 첫타자 사사구 비율2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/삼성 불펜투수 첫타자 사사구 비율2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/삼성 불펜투수 첫타자 사사구 비율.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/팀별 불펜투수 첫타자 사사구 비율2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/9월 2주/팀별 불펜투수 첫타자 사사구 비율2.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/팀별 불펜투수 첫타자 사사구 비율2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/삼성 불펜투수 첫타자 사사구 비율2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/팀별 불펜투수 첫타자 사사구 비율2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/9월 2주/팀별 불펜투수 첫타자 사사구 비율2.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/팀별 불펜투수 첫타자 사사구 비율2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/삼성 불펜투수 첫타자 사사구 비율2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification 개인.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/뷰캐넌 하패 2s 이후.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')

## ---(Fri Sep 24 09:47:46 2021)---
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/뷰캐넌 하패 2s 이후.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py')
runcell(3, 'C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py')
runcell(4, 'C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runcell(4, 'C:/Users/LIONS/.spyder-py3/9월 4주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/x스탯2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/9월 4주/x스탯2.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/x스탯2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/9월 4주/x스탯2.py')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/타자 리더보드(타구).py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/타자 리더보드(plate discipline).py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')

## ---(Sat Sep 25 13:20:22 2021)---
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification 개인.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification 개인.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Tue Sep 28 13:15:09 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/구속에 따른 도달거리 차이.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/팀별 hittype.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runfile('C:/Users/LIONS/.spyder-py3/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3')
runcell(1, 'C:/Users/LIONS/.spyder-py3/9월 4주/팀별 힛타입(xgb).py')

## ---(Tue Oct  5 17:43:10 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Thu Oct  7 09:38:14 2021)---
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/R2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')

## ---(Fri Oct  8 09:35:42 2021)---
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runcell(1, 'C:/Users/LIONS/.spyder-py3/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/투수 리더보드(구종 속성).py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/투수 리더보드(구종 속성).py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')

## ---(Sat Oct  9 13:20:17 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')

## ---(Sat Oct  9 14:18:46 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 2주/영상.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 2주/영상.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')

## ---(Sat Oct  9 16:11:02 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')

## ---(Sat Oct  9 16:14:04 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled3.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled3.py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled3.py')
runcell(3, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled3.py')
runcell(4, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled3.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled3.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled5.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled5.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')

## ---(Tue Oct 12 17:23:29 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/영상 이름 수정.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/영상 이름 수정.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification 개인.py', wdir='C:/Users/LIONS/.spyder-py3')

## ---(Wed Oct 13 11:23:48 2021)---
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification 개인.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 수정 후 애니메이션.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/9월 2주/구종 무브먼트 comparison.py', wdir='C:/Users/LIONS/.spyder-py3/9월 2주')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종 무브먼트 comparison 2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/파일 병합.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification 개인.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/pitch_type_classification 개인.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/9월 3주/구종분류 확인 2D.py', wdir='C:/Users/LIONS/.spyder-py3/9월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/파일 병합.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/파일 병합.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/파일 병합.py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/파일 병합.py')
runfile('C:/Users/LIONS/.spyder-py3/파일 병합.py', wdir='C:/Users/LIONS/.spyder-py3')
runcell(2, 'C:/Users/LIONS/.spyder-py3/파일 병합.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')

## ---(Thu Oct 14 11:01:17 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/구장 별 RE.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py')
runcell(3, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(타석 당 수치 기반).py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled3.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled3.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(타석 당 수치 기반).py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(타석 당 수치 기반).py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(타석 당 수치 기반).py')
runcell(3, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(타석 당 수치 기반).py')
runcell(4, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(타석 당 수치 기반).py')
runfile('C:/Users/LIONS/.spyder-py3/9월 4주/x스탯2.py', wdir='C:/Users/LIONS/.spyder-py3/9월 4주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled4.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')

## ---(Fri Oct 15 13:53:09 2021)---
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/예전 힛타입 분류.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')

## ---(Sat Oct 16 11:25:31 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/영상 이름 수정.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled0.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/예전 힛타입 분류.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')

## ---(Sun Oct 17 11:40:50 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/영상 이름 수정.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/YBY 성적 R2.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')

## ---(Tue Oct 19 12:54:27 2021)---
runcell(0, 'C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runcell(2, 'C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/8월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/8월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled1.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 4주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/10월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 4주/untitled2.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 4주/뜬공 홈런 비율.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 4주/뜬공 홈런 비율.py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 4주/뜬공 홈런 비율.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 4주/뜬공 홈런 비율.py', wdir='C:/Users/LIONS/.spyder-py3/10월 4주')
runfile('C:/Users/LIONS/.spyder-py3/10월 4주/발사각 루타 분포.py', wdir='C:/Users/LIONS/.spyder-py3/10월 4주')

## ---(Fri Oct 22 12:45:01 2021)---
runfile('C:/Users/LIONS/.spyder-py3/영상 이름 수정.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')

## ---(Fri Oct 22 13:55:55 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')

## ---(Fri Oct 22 14:29:18 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 4주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 4주')

## ---(Fri Oct 22 18:09:57 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled2.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled1.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled1.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled1.py')

## ---(Sat Oct 23 11:52:42 2021)---
runfile('C:/Users/LIONS/.spyder-py3/영상 이름 수정.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/플라이볼 홈런 관계.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py')

## ---(Sun Oct 24 09:58:50 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')

## ---(Sun Oct 24 16:19:16 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터.py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(타석 당 수치 기반).py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')

## ---(Wed Oct 27 11:05:49 2021)---
runfile('C:/Users/LIONS/.spyder-py3/15경기 스윙률.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/라팍 그리기(정면).py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/시프트 자료.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/untitled0.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')
runfile('C:/Users/LIONS/.spyder-py3/10월 4주/투수 리더보드(구종 구사 2).py', wdir='C:/Users/LIONS/.spyder-py3/10월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 4주/투수 리더보드(구종 구사 2).py')
runfile('C:/Users/LIONS/.spyder-py3/10월 4주/투수 리더보드(구종 구사 2).py', wdir='C:/Users/LIONS/.spyder-py3/10월 4주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 4주/투수 리더보드(구종 구사 2).py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(타석 당 수치 기반).py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(타석 당 수치 기반).py')
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(xwOBA 모델링 기반).py')

## ---(Wed Oct 27 17:10:08 2021)---
runcell(0, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(xwOBA 모델링 기반).py')
runcell(1, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(xwOBA 모델링 기반).py')
runcell(2, 'C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(xwOBA 모델링 기반).py')
runfile('C:/Users/LIONS/.spyder-py3/10월 3주/파크팩터 보정 wOBA(타석 당 수치 기반).py', wdir='C:/Users/LIONS/.spyder-py3/10월 3주')

## ---(Fri Oct 29 16:45:28 2021)---
runfile('C:/Users/LIONS/.spyder-py3/영상 이름 수정.py', wdir='C:/Users/LIONS/.spyder-py3')
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')

## ---(Fri Oct 29 16:56:41 2021)---
runfile('C:/Users/LIONS/.spyder-py3/10월 2주/영상 자막 첨부 및 병합.py', wdir='C:/Users/LIONS/.spyder-py3/10월 2주')